serverFiles:
  prometheus.yml:
    scrape_configs:
    - job_name: "game_1"
      scrape_interval: 5s
      static_configs:
        - targets: 
          - "game-metrics.default.svc.cluster.local:14503"

server:
  service:
    type: LoadBalancer
    servicePort: 9090
  global:
    scrape_interval: 5s
