datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: prod-prometheus-server.default.svc.cluster.local
      access: proxy
      isDefault: true

      