datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.prod.svc.cluster.local:9090
      access: proxy
      isDefault: true
    
service:
  type: LoadBalancer
  port: 3000

